name: CI

on:
  push:
    branches: [ master, next, perf, ci ]
  pull_request:
    branches: [ master, next ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.1.4
      - run: sudo apt install -y valgrind libcmocka-dev
      - run: npm install
      - run: npm run build
      - run: npm test
